sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

before_install:
  - ci/travis/decrypt-all.sh
  - pip install -U -r ci/requirements.txt

install:
  - pip install ./moclo ./moclo-*

before_script:
  - pip install -U -r tests/requirements.txt

script:
  - green -T

after_script:
  - python -m codecov
  - python -m codacy

before_deploy:
  - python ci/travis/before-deploy.py

deploy:
  provider: script
  script: twine upload --skip-existing dist/*
  skip_cleanup: true
  on:
    tags: true
    python: 3.8
    repo: althonos/moclo

notifications:
  email:
  - althonosdev@gmail.com
