sudo: false
language: python
cache: pip

services:
  - docker

stages:
  - name: CPython
  - name: PyPy

# .deploy: &deploy
#   provider: script
#   script: twine upload --skip-existing dist/*
#   skip_cleanup: true
#   on:
#     tags: true
#     repo: althonos/moclo

.test-native: &test-native
  before_install:
    - ci/travis/decrypt-all.sh
    - pip install -U -r ci/requirements.txt
  install:
    - pip install ./moclo ./moclo-ytk ./moclo-cidar ./moclo-ecoflex
  before_script:
    - pip install -U -r tests/requirements.txt
  script:
    - green
  after_script:
    - python -m codecov
    - python -m codacy

.test-docker: &test-docker
  before_script:
    - docker pull $IMAGE
  script:
    - docker run -it -v "$TRAVIS_BUILD_DIR":/py $IMAGE sh -c /py/ci/travis/test-docker.sh

jobs:
  include:

    # Tests using the default Travis-CI provided Python
    - python: pypy
      stage: PyPy
      <<: *test-native
    - python: pypy3
      stage: PyPy
      <<: *test-native

    # Tests against CPython using the native Travis-CI Python binaries
    - python: 2.7
      stage: CPython
      <<: *test-native
    - python: 3.4
      stage: CPython
      <<: *test-native
    - python: 3.5
      stage: CPython
      <<: *test-native
    - python: 3.6
      stage: CPython
      <<: *test-native
      before_deploy:
        - python ci/travis/before-deploy.py
      deploy:
        provider: script
        script: twine upload --skip-existing dist/*
        skip_cleanup: true
        on:
          tags: true
          repo: althonos/moclo

    # Tests using a Docker image
    - env:
      - IMAGE=python:3.7
      stage: CPython
      <<: *test-docker


notifications:
  email:
  - althonosdev@gmail.com
