sudo: false
language: python
cache: pip

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7-dev'
- pypy
- pypy3.5

matrix:
  allow_failures:
  - python: pypy
  - python: pypy3.5
  - python: 3.7-dev

before_install:
- ci/travis/decrypt-all.sh
- pip install -U -r ci/requirements.txt

install:
- pip install ./moclo
- pip install ./moclo-ytk

before_script:
- pip install -U -r tests/requirements.txt

script:
- green

after_script:
- python -m codecov
- python -m codacy

before_deploy:
- cd moclo     && python setup.py check -rms sdist bdist_wheel -d ../dist
- cd moclo-ytk && python setup.py check -rms sdist bdist_wheel -d ../dist

deploy:
  provider: script
  script: twine upload --skip-existing dist/moclo
  skip_cleaning: true
  on:
    tags: true
    python: '3.6'
    repo: althonos/moclo

notifications:
  email:
  - althonosdev@gmail.com
